fix: add semicolon to avoid possible crashes (#317)
**Summary**
Adding a semicolon makes code more robust when integrated (concatenated)
with other files

**Test plan**
I tried integrating with [docz](https://github.com/pedronauck/docz) and after I added `linaria/loader` to docz bundler configuration, I got an error like this:

```
Failed to compile.

./src/ui/components/StatementList/NewItemInput/NewItemInput.tsx
SyntaxError: /sample-project/src/ui/components/StatementList/NewItemInput/NewItemInput.tsx: Unexpected token, expected ";" (20:150)

  18 | ;
  19 |
> 20 | require("/sample-project/.linaria-cache/src/ui/components/StatementList/NewItemInput/NewItemInput.linaria.css")try {
     |                                                                                                                ^
  21 |     // @ts-ignore
  22 |     NewItemInput.displayName = "NewItemInput";
  23 |     // @ts-ignore
```

As I understand, the `tsx` file that was modified by linaria got concatenated with some other file which began with a `try` statement. Therefore a syntax error was produced.

I believe that adding a semicolon after the import statement is a safe way to avoid such problems.